/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package com.smartitengineering.user.observer;

/**
 *
 * @author modhu7
 */
public enum ObserverNotification {
  CREATE_ORGANIZATION,
  UPDATE_ORGANIZATION,
  DELETE_ORGNIZATION,
  CREATE_USER_PERSON,
  UPDATE_USER_PERSON,
  DELETE_USER_PERSON,
  CREATE_PERSON,
  UPDATE_PERSON,
  DELETE_PERSON,
  CREATE_USER,
  UPDATE_USER,
  DELETE_USER,
  CREATE_USER_GROUP,
  UPDATE_USER_GROUP,
  DELETE_USER_GROUP,
  CREATE_SECURED_OBJECT,
  UPDATE_SECURED_OBJECT,
  DELETE_SECURED_OBJECT,
  CREATE_PRIVILEGE,
  UPDATE_PRIVILEGE,
  DELETE_PRIVILEGE,
  CREATE_ROLE,
  UPDATE_ROLE,
  DELETE_ROLE;
}
